# Configuração do servidor
server.port=8080

# Configuração do H2 Database
spring.datasource.url=jdbc:h2:mem:deliverydb
spring.datasource.driverClassName=org.h2.Driver
spring.datasource.username=sa
spring.datasource.password=

# Console H2
spring.h2.console.enabled=true
spring.h2.console.path=/h2-console

# JPA/Hibernate
spring.jpa.database-platform=org.hibernate.dialect.H2Dialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true

# Configurações de desenvolvimento
spring.devtools.restart.enabled=true

#
jwt.secret=chave-secreta-bem-longa-para-assinatura-do-token-jwt-2026
jwt.expiration=86400000

# Expor todos os endpoints do Actuator
management.endpoints.web.exposure.include=*

# Mostrar detalhes do /actuator/health
management.endpoint.health.show-details=always

# Nível de log da aplicação
logging.level.root=INFO
logging.level.com.deliverytech=DEBUG